name: Manius_Announcements
version: 1.0
main: com.example.maniusannouncements.ManiusAnnouncements
api-version: 1.20

commands:
  maniusactionbar:
    description: Wysyła ogłoszenie na ActionBarze
    permission: manius.admin
    aliases: [mab]
  maniusactionbarusun:
    description: Usuwa obecny Actionbar
    permission: manius.admin
    aliases: [mabusun]
  maniusbossbar:
    description: Wysyła ogłoszenie na BossBarze
    permission: manius.admin
    aliases: [mbb]
  maniusbossbarusun:
    description: Usuwa obecny BossBar
    permission: manius.admin
    aliases: [mbbusun]
  maniuschat:
    description: Wysyła ogłoszenie na czacie
    permission: manius.admin
    aliases: [mchat]
  maniustitle:
    description: Wysyła ogłoszenie Title na środku ekranu
    permission: manius.admin
    aliases: [mtitle]
  maniusannouncements:
    description: Główna komenda pluginu
    permission: manius.admin
    aliases: [mannounce]
